apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: redax-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redax-api
  minReplicas: 3
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: redax-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redax-worker
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
