apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redax
resources:
  - namespace.yaml
  - configmap.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - service.yaml
  - pdb.yaml
  - hpa.yaml
  - network-policy.yaml
images:
  - name: ghcr.io/sachncs/redax
    newName: ghcr.io/sachncs/redax
    digest: sha256:1ce7d76f5fede54c3cb59f31ceb79e47fb5663996a5bcf0588f8cacb3f454007
