apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redax
resources:
  - namespace.yaml
  - configmap.yaml
  - audit-pvc.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - service.yaml
  - pdb.yaml
  - hpa.yaml
images:
  - name: ghcr.io/sachncs/redax
    newTag: v0.1.0
