apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redax-api
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redax
      app.kubernetes.io/component: api
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              redax.ingress-access: "true"
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 6380
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redax-worker
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redax
      app.kubernetes.io/component: worker
  policyTypes: [Ingress, Egress]
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 6380
