apiVersion: v1
kind: Service
metadata:
  name: redax-api
  labels:
    app.kubernetes.io/name: redax
spec:
  selector:
    app.kubernetes.io/name: redax
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
